export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

export const GET_USERS_MORE_SUCCESS = "GET_USERS_MORE_SUCCESS"
export const GET_USERS_MORE_FAILURE = "GET_USERS_MORE_FAILURE"

export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST"
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE"

export const GET_MORE_BLOGS_SUCCESS = "GET_MORE_BLOGS_SUCCESS"
export const GET_MORE_BLOGS_FAILURE = "GET_MORE_BLOGS_FAILURE"

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"