export const REACTION_BLOG_SUCCESS = "REACTION_BLOG_SUCCESS"
export const REACTION_BLOG_FAILURE = "REACTION_BLOG_FAILURE"

export const UNREACTION_BLOG_SUCCESS = "UNLIKE_BLOG_SUCCESS"
export const UNREACTION_BLOG_FAILURE = "UNREACTION_BLOG_FAILURE"

export const REACTION_COMMENT_SUCCESS = "REACTION_COMMENT_SUCCESS"
export const REACTION_COMMENT_FAILURE = "REACTION_COMMENT_FAILURE"

export const UNREACTION_COMMENT_SUCCESS = "UNREACTION_COMMENT_SUCCESS"
export const UNREACTION_COMMENT_FAILURE = "UNREACTION_COMMENT_FAILURE"