export const SET_USER = "SET_USER"

export const GET_PROFILE_BY_ID_SUCCESS = "GET_PROFILE_BY_ID_SUCCESS"
export const GET_PROFILE_BY_ID_FAILURE = "GET_PROFILE_BY_ID_FAILURE"

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE"

export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS"
export const UNFOLLOW_USER_FAILURE = "UNFOLLOW_USER_FAILURE"